apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T13:05:54Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "4286"
  uid: 004eb3a9-9f5d-47b0-9307-46f6418063dd
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.108.228.14
  clusterIPs:
  - 10.108.228.14
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30420
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
